name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Linux (Ruby ${{ matrix.ruby-version }})
    strategy:
      matrix:
        ruby-version: ['3.3', '3.4']
        json-parser: ['JSON', 'Oj', 'Yajl']

    steps:
    - uses: actions/checkout@v4
    - name: Install PostgreSQL client headers
      run: sudo apt-get update && sudo apt-get install -y libpq-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Verify pg loads
      run: bundle exec ruby -e 'require "pg"'
    - name: Run tests (ubuntu)
      env:
        JSON_PARSER: ${{ matrix.json-parser }}
      run: bundle exec rake

#  openbsd:
#    runs-on: ubuntu-latest
#    name: OpenBSD
#    continue-on-error: true
#    env:
#      bundler: "bundle33"
#    steps:
#    - uses: actions/checkout@v4
#    - name: Run tests
#      uses: vmactions/openbsd-vm@v1
#      with:
#        copyback: false
#        envs: "bundler"
#        run: |
#          pkg_add ruby-3.4.9
#          pkg_add postgresql-client
#          bundle33 install
#          bundle33 exec ruby33 -e 'require "pg"'
#          bundle33 exec rake

#  netbsd:
#    runs-on: ubuntu-latest
#    name: NetBSD
#    continue-on-error: true
#    steps:
#    - uses: actions/checkout@v4
#    - name: Run tests
#      uses: vmactions/netbsd-vm@v1
#      with:
#        copyback: false
#        run: |
#          pkg_add ruby-3.3.11
#          bundle33 install
#          bundle33 exec rake

#  freebsd:
#    runs-on: ubuntu-latest
#    name: FreeBSD
#    continue-on-error: true
#    steps:
#    - uses: actions/checkout@v4
#    - name: Run tests
#      uses: vmactions/freebsd-vm@v1
#      with:
#        copyback: false
#        run: |
#          pkg-static install -y pkgconf rubygem-bundler
#          bundle install
#          bundle exec rake
